services:
  bob:
    restart: always
    build:
      context: .
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      USER_NAME: "bob"
  seed1:
    restart: always
    build:
      context: .
    environment:
      PORT: 3000
      USER_NAME: "seed1"
  seed2:
    restart: always
    build:
      context: .
    environment:
      PORT: 3000
      USER_NAME: "seed2"
  sally:
    restart: always
    build:
      context: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      USER_NAME: "sally"
